In [1]:
print(10/3)

3.3333333333333335


In [2]:
print(10//3)

3


In [3]:
print(10%3)

1


In [4]:
table = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(table[1][2])  # Output: 6

6


In [5]:
table

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
print(table[0][0])  # Output: 1

1


In [8]:
print(table[2][1])

8


In [9]:
menu = {"item1": 10, "item2": 20, "item3": 30}
print(menu["item2"])

20


In [10]:
x =1  
if x > 0:
    x = -x
    x= -x
print(x)

1


In [11]:
x =1  
if x > 0:
    x = -x
# x= -x
print(x)

-1


In [12]:
x =1  
if x > 0:
    x = -x
x= -x
print(x)

1


In [14]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x[1][2])  # Output: 6

6


In [15]:
print(type(x))  # Output: <class 'numpy.ndarray'>)

<class 'numpy.ndarray'>


In [ ]:
class Pokemon:
    def __init__(self, name, type, level):
        self.name = name
        self.type = type
        self.level = level

    def attack(self):
        print(f"{self.name} attacks with {self.type} type!")

    def level_up(self):
        self.level += 1
        print(f"{self.name} leveled up to {self.level}!")
    
# what is  self ? ans : It refers to the instance of the class itself. the current object that is being created or manipulated. It allows you to access the attributes and methods of the class within its own definition.

In [ ]:
pika = Pokemon("Pikachu", "Electric", 5) # Create an instance of the Pokemon class
pika.attack()  # Output: Pikachu attacks with Electric type!
pika.level_up()  # Output: Pikachu leveled up to 6!

Pikachu attacks with Electric type!
Pikachu leveled up to 6!


In [18]:
# 2d list
score_table = [['Alice', 20, 30], ['Bob', 40, 50], ['Charlie', 70, 80]]

In [19]:
score_table[0][0]  # Output: 'Alice'

'Alice'

In [20]:
score_table

[['Alice', 20, 30], ['Bob', 40, 50], ['Charlie', 70, 80]]

In [21]:
a = [1, 2, 3]
b = [4, 5, 6]
a+b

[1, 2, 3, 4, 5, 6]

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a+b

array([5, 7, 9])

In [23]:
np.add(a, b)  # Output: array([5, 7, 9])

array([5, 7, 9])

In [24]:
np.exp(a)  # Output: array([ 2.71828183,  7.3890561 , 20.08553692]) 

array([ 2.71828183,  7.3890561 , 20.08553692])

In [25]:
np.log(a)  # Output: array([0.        , 0.69314718, 1.09861229])

array([0.        , 0.69314718, 1.09861229])

In [26]:
np.sin(a)  # Output: array([0.84147098, 0.90929743, 0.14112001])

array([0.84147098, 0.90929743, 0.14112001])

In [28]:
a

array([1, 2, 3])

In [27]:
c=5
np.add(a,c)

array([6, 7, 8])

In [1]:
# indexing (1D array)

In [10]:
import numpy as np
l1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [11]:
l1[[0, 3, 5]]  # Output: array([0, 5, 7])

array([1, 4, 6])

In [12]:
l1[1:7:2]  # Output: array([3, 5, 7])

array([2, 4, 6])

In [13]:
l1[1:7]

array([2, 3, 4, 5, 6, 7])

In [14]:
l1[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
l1[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
l1[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [17]:
l1[0]  # Output: 0

np.int64(1)

In [18]:
l1[1]

np.int64(2)

In [19]:
print(l1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
